manifest:
  self:
    # This repository should be cloned to
    path: example-application

  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
    # the NCS repository
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.8.0
      import: true
